# This file was generated by GoReleaser. DO NOT EDIT.
cask "gws-tui" do
  version "0.1.0-rc.1"

  on_macos do
    on_intel do
      sha256 "d9c6debcebf3a707d08af05370694072ca17e18313abe2fcaa41ccb2530e0c0d"
      url "https://github.com/fabhiansan/gws-tui/releases/download/v#{version}/gws-tui_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "347d4ea48bf6e604af291eac045e2e1df1b9e1c87d0aad80878691efbbe0dc94"
      url "https://github.com/fabhiansan/gws-tui/releases/download/v#{version}/gws-tui_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "832921f2c42d3fc5b8de7779aba624db0dd33e33cc96b885a8ac534078a2b6d6"
      url "https://github.com/fabhiansan/gws-tui/releases/download/v#{version}/gws-tui_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e09afc5a0f68c54f9249eee37b9c39fb511354fe0135c6a7bd8f8c38ff8cc1c4"
      url "https://github.com/fabhiansan/gws-tui/releases/download/v#{version}/gws-tui_linux_arm64.tar.gz"
    end
  end

  name "gws-tui"
  desc "Terminal UI for Google Workspace (Chat, Mail, Calendar, Meet)"
  homepage "https://github.com/fabhiansan/gws-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gws-tui"

  # No zap stanza required

  caveats <<~EOS
    gws-tui calls the upstream Google Workspace CLI for live Workspace data.
    Install it separately:
        brew install googleworkspace-cli
      or:
        npm install -g @googleworkspace/cli

    Then authenticate once:
        gws auth login

    If the upstream gws is not on PATH, point gws-tui at it:
        export GWS_TUI_UPSTREAM=/path/to/upstream/gws

    First release ships unsigned; macOS Gatekeeper may prompt on first run.
    If it does, right-click → Open, or run:
        xattr -dr com.apple.quarantine "$(brew --prefix)/bin/gws-tui"
  EOS
end
