# This file was generated by GoReleaser. DO NOT EDIT.
cask "gws-tui" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "6746717f6f6feb7f35963b97445fc23ad2a0dfa4cb7eaa64af559e86096f8e58"
      url "https://github.com/fabhiansan/gws-tui/releases/download/v#{version}/gws-tui_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cfdb63d377539b8564eff5cfafd7ec7fb5111c37986f87cf0536b294d34bc046"
      url "https://github.com/fabhiansan/gws-tui/releases/download/v#{version}/gws-tui_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "579e6c5177efa9d03cec5c80d7155f096cd3bd3ecbe3c2dcd307be1118da9357"
      url "https://github.com/fabhiansan/gws-tui/releases/download/v#{version}/gws-tui_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "953f4ebf60ec73c29c230e3b456e7c42830062d748bc3d9ed0da002e3d066ab4"
      url "https://github.com/fabhiansan/gws-tui/releases/download/v#{version}/gws-tui_linux_arm64.tar.gz"
    end
  end

  name "gws-tui"
  desc "Terminal UI for Google Workspace (Chat, Mail, Calendar, Meet)"
  homepage "https://github.com/fabhiansan/gws-tui"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gws-tui"

  # No zap stanza required

  caveats <<~EOS
    gws-tui calls the upstream Google Workspace CLI for live Workspace data.
    Install it separately:
        brew install googleworkspace-cli
      or:
        npm install -g @googleworkspace/cli

    Then authenticate once:
        gws auth login

    If the upstream gws is not on PATH, point gws-tui at it:
        export GWS_TUI_UPSTREAM=/path/to/upstream/gws

    First release ships unsigned; macOS Gatekeeper may prompt on first run.
    If it does, right-click → Open, or run:
        xattr -dr com.apple.quarantine "$(brew --prefix)/bin/gws-tui"
  EOS
end
